# --- !Ups
CREATE TABLE IMAGES (
  USER_ID INT NOT NULL,
  URL_SMALL VARCHAR(1000) NOT NULL,
  URL_LARGE VARCHAR(1000) NOT NULL,
  CONSTRAINT USER_ID_UK UNIQUE (USER_ID)
);

COMMENT ON TABLE IMAGES IS 'Table that stores all users images.';

COMMENT ON COLUMN IMAGES.USER_ID IS 'User ID.';
COMMENT ON COLUMN IMAGES.URL_SMALL IS 'URL of the small image.';
COMMENT ON COLUMN IMAGES.URL_LARGE IS 'URL of the large image.';

# --- !Downs
DROP TABLE IMAGES;

